### ISSUE TITLE
XML :: simple cannot locate

### ISSUE THREAD

**Issue by jasonbhn** [tseemann/prokka#297]
Hi 
I was trying to install prokka with Bioconda. But it keeps giving me this message: 
```
Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /home/gerwick-lab/anaconda3/bin/../perl5 /home/gerwick-lab/perl5/lib/perl5/5.26.0/x86_64-linux-thread-multi /home/gerwick-lab/perl5/lib/perl5/5.26.0 /home/gerwick-lab/perl5/lib/perl5/x86_64-linux-thread-multi /home/gerwick-lab/perl5/lib/perl5 /home/gerwick-lab/anaconda3/lib/site_perl/5.26.0/x86_64-linux-thread-multi /home/gerwick-lab/anaconda3/lib/site_perl/5.26.0 /home/gerwick-lab/anaconda3/lib/5.26.0/x86_64-linux-thread-multi /home/gerwick-lab/anaconda3/lib/5.26.0 .) at /home/gerwick-lab/anaconda3/bin/prokka line 27.
BEGIN failed--compilation aborted at /home/gerwick-lab/anaconda3/bin/prokka line 27.

```
Does a solution for avoiding this dependency exist? I tried install this and it just creates more problem regarding perl. 
Thank you.

**Comment by Russel88** [comment]
FYI, there is still an error in the README:
`conda install -c bioconda -c conda-forge prokka`

**Comment by tseemann** [comment]
THanks @Russel88  - fixed now!

**Comment by avrajit** [comment]
hi I am geting same problem. I did
_conda install -c conda-forge -c bioconda prokka_
when trying to run 

Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /home/XX/anaconda3/bin/../perl5 /home/XX/anaconda3/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi /home/XX/anaconda3/lib/perl5/site_perl/5.22.2 /home//XXanaconda3/lib/perl5/5.22.2/x86_64-linux-thread-multi /home/XX/anaconda3/lib/perl5/5.22.2 .) at /home/avrajit/anaconda3/bin/prokka line 27.
BEGIN failed--compilation aborted at /home/XX/anaconda3/bin/prokka line 27

please help

**Comment by rec3141** [comment]
I had the same problem, even when using the correct order
```conda install -c conda-forge -c bioconda prokka```

It seems Perl was trying to use libraries from the wrong place (~/.conda) for some reason.

I fixed it by doing 
```export PERL5LIB=`pwd`/lib/site_perl/5.26.2:`pwd`/lib/5.26.2```

**Comment by mdtorohernando** [comment]
I still have this problem by using 
`conda install -c conda-forge -c bioconda prokka`

Please, can you help to me?
Thanks

**Comment by JPegorino** [comment]
I'm still getting this issue on 06/09/2019 after installing with either `conda install -c conda-forge -c bioconda prokka` or `conda install -c conda-forge -c bioconda -c defaults prokka`  .

I'm in a brand new environment containing only what was downloaded with the above commands. 
`which prokka` gives my path to `software/conda_envs/jamieG/envs/annotation/bin/prokka`
and `which perl` gives the same path ending `/bin/perl` . Running `export PERL5LIB=`pwd`/lib/site_perl/5.26.2:`pwd`/lib/5.26.2` for my version of perl (5.22.2) didn't help me.

I hope the problem isn't with a conflicting perl installation because I'm running this with a sun grid engine on a shared high compute cluster with perl already installed in /usr/bin/perl , which I can't change. How can I check where prokka/perl are looking for files and how could I change that?  - Thanks

**Comment by tseemann** [comment]
@JPegorino if you are using conda then I don't understand what the problem is. make sure you activate the conda  `annotation` environment in your SGE job submission script. prokka uses the first Perl in your PATH, and you can control this. your `$HOME/software/condabin` should be the first thing in your PATH. Do not uses any `module load` software.

**Comment by JPegorino** [comment]
solved -- I _was_ using `module load` software and specifically, my problem was loading a default, out of date version of anaconda (4.3.1). It works using a more up-to-date version (5.0.1 with `export PATH=$PATH:/exports/applications/apps/SL7/anaconda/5.0.1/bin` ) and works with module load too if I specify the newer version. Thanks for the support, @tseemann !

**Comment by humbertoibanez** [comment]
> Hi I was trying to install prokka with Bioconda. But it keeps giving me this message:
> 
> ```
> Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /home/xx/anaconda3/bin/../perl5 /home/xx/perl5/lib/perl5/5.26.0/x86_64-linux-thread-multi /home/xx/perl5/lib/perl5/5.26.0 /home/xx/perl5/lib/perl5/x86_64-linux-thread-multi /home/xx/perl5/lib/perl5 /home/xx/anaconda3/lib/site_perl/5.26.0/x86_64-linux-thread-multi /home/xx/anaconda3/lib/site_perl/5.26.0 /home/xx/anaconda3/lib/5.26.0/x86_64-linux-thread-multi /home/xx/anaconda3/lib/5.26.0 .) at /home/xx/anaconda3/bin/prokka line 27.
> BEGIN failed--compilation aborted at /home/xx/anaconda3/bin/prokka line 27.
> ```
> 
> Does a solution for avoiding this dependency exist? I tried install this and it just creates more problem regarding perl. Thank you.

I solved the issue related by @jasonbhn by searching where were the Simple.pm script 
```
updatedb
locate Simple.pm | grep XML

```
Discovered the path I added it in the 'use lib' instruction at the prokka script (/path/to/anaconda3/pkgs/prokka-1.12-1/bin/prokka) installed by the conda 
`use lib '/usr/local/anaconda3/lib/perl5/site_perl/5.22.0/';`
Some lines after this adding there's a call to the XML/Simple.pm script
`use XML::Simple;`
The issue was that the '@INC' only contained the path to the 5.22.2 library and not to the 5.22.0 earliest version where conda had installed the XML/Simple.pm script.
