### ISSUE TITLE
tbl2asn problem

### ISSUE THREAD

**Issue by AiramBen** [tseemann/prokka#303]
Hello
I was trying to run Prokka in ubuntu, but a mistake has occurred:

[12:33:32] Looking for 'tbl2asn' - found /usr/bin/tbl2asn
[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
[12:33:32] Determined tbl2asn version is 20.0
[12:33:32] Prokka needs tbl2asn 24.3 or higher. Please upgrade and try again.

I downloaded the latest version of Prokka (Prokka 1.13) here in GitHub, and I've tried to replace the tbl2asn executable with the updated one  (I read this answer in previous questions about this mistake), downloaded from here and from NCBI, but the mistake persists. 

How can I solve this problem?

Thank you

**Comment by tseemann** [comment]
Which one did you replace with which?

The above says it's using the one in /use/bin ?  Is that the latest version? Try running it directly on command line to check.

**Comment by AiramBen** [comment]
I replaced /prokka/binaries/linux/tbl2asn with the [NCBI one](https://www.ncbi.nlm.nih.gov/genbank/tbl2asn2/). I'm trying to run Prokka in the downloaded file from here (so I assumed that this is the most recent version). If you mean /usr/bin/tbl2asn version, the same happens, when I running on command line, the next message appears:

[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
[tbl2asn] You must supply either an input file (-i) or an input directory (-p).
Use -p . to specify the current directory.

Sorry if I don't understand (I'm new at this) but I don't know exactly what to do.

Thank you

**Comment by tseemann** [comment]
The one in Prokka will only be used if you don't have one on your system.
You do have one, in /usr/bin but it is too old.
You have a newer one in Prokka but it will not be used due to the one in /usr/bin
You need to move, delete, upgrade or rename the one in /usr/bin and it will use the prokka one.

The ones provided by prokka a "last resort" but in this case you need it, but am not willing to over-ride your system PATH. You could also manually add prokka/binaries/linux to your PATH earlier than /usr/bin.

Hope this helps you get it working.

It is suggested you use conda or brew to install prokka and other tools in future to avoid these clashes. Sorry i can't be of more help.

**Comment by libertinerosessanchez** [comment]
I have smoothly running prokka but the following errors came out.
Could not run command: tbl2asn -V b -a r10k -l paired-ends -M b -N 1 -y 'Annotated using prokka 1.12 from https://github.com/tseemann/prokka' -Z PB3_prokka_annot\/PB3\.err -i PB3_prokka_annot\/PB3\.fsa 2> /dev/null
** i tried to resolve by directly runnign the commandline removing 2> /dev/null but it did not work.

The other ones I'm running do not have .err file and just hung in this line:
Running: tbl2asn -V b -a r10k -l paired-ends -M b -N 1 -y 'Annotated using prokka 1.12 from https://github.com/tseemann/prokka' -Z PA1_prokka_annot\/PA1\.err -i PA1_prokka_annot\/PA1\.fsa 2> /dev/null

Please help me on this. I had all output files generated except .gbk and .asn. Is there a way by which to continue or resolve the tbl2asn since I had ran all files for 5 days already.
Thank you

**Comment by libertinerosessanchez** [comment]
All my runs get stucked in here:
Fixed 4896 colliding /gene names.
[21:47:37] Adding /locus_tag identifiers
[21:47:42] Assigned 213390 locus_tags to CDS and RNA features.
[21:47:42] Writing outputs to PB3_prokka_annot/
[21:51:20] Generating annotation statistics file
[21:51:22] Generating Genbank and Sequin files
[21:51:22] Running: tbl2asn -V b -a r10k -l paired-ends -M b -N 1 -y 'Annotated using prokka 1.12 from https://github.com/tseemann/prokka' -Z PB3_prokka_annot\/PB3\.err -i PB3_prokka_annot\/PB3\.fsa 2> /dev/null
[09:27:50] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M b -N 1 -y 'Annotated using prokka 1.12 from https://github.com/tseemann/prokka' -Z PB3_prokka_annot\/PB3\.err -i PB3_prokka_annot\/PB3\.fsa 2> /dev/null

What should I do?

**Comment by tseemann** [comment]
` 213390 locus_tags `  that is not a bacterial genome
you must be using a metagenome in prokka
it is not designed for tjat and tbl2asn will probably crash or never finish
try commenting out the line.

**Comment by libertinerosessanchez** [comment]
What would be my commandline then? ALl the output files were generated except the gbk and asn files which are of course impt for my submission

**Comment by felipelira** [comment]
Because I found this post to solve looking for some answer to my problem, I share with you my solution for the case that another one arrives here.

$ wget -N ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/linux64.tbl2asn.gz
$ gunzip linux64.tbl2asn.gz
$ chmod +x linux64.tbl2asn
$ mv linux64.tbl2asn /usr/local/bin/tbl2asn
$ tbl2asn --help

**Comment by tseemann** [comment]
@libertinerosessanchez i wish you luck with your submission. NCBI is very strict now. Did you remove all contigs < 200 bp? They are not allowed.

**Comment by tseemann** [comment]
@felipelira that will work if you have `/usr/local/bin` in your `$PATH` yes.  

I really recommend you install prokka etc using Conda or Brew so you don't need to use these kludges.

**Comment by felipelira** [comment]
@tseemann For sure, I removed the contigs under 200bp. At this point I learned on the hard way submitting genomes to NCBI but for the moment I am using PROKKA to analyzed differente genomes obtained from different sources and annotated under different methods. I am "normalizing" the annotation for all genomes I am working with.
I installed PROKKA using conda but because I did some minimal changes, such as parameters to call prodigal, I fixed the tbl2asn problem as commented before. It was an emergency.
Any way to contact you? 
felipelira3 at gmail dot com

**Comment by tseemann** [comment]
You are contacting me right here now :)

**Comment by Arkadiy-Garber** [comment]
With the latest install using condo today, prokka still crashes due to the tbl2asn issue. After manually going through the script an commenting out relevant lines, it seems to work.

**Comment by Arkadiy-Garber** [comment]
Never mind: Now crashes at this step:

[13:52:52] Generating annotation statistics file
[13:52:54] Generating Genbank and Sequin files
[13:52:54] Deleting unwanted file: prokka-1_core9/errorsummary.val
[13:52:54] Deleting unwanted file: prokka-1_core9/1_core9.dr
[13:52:54] Deleting unwanted file: prokka-1_core9/1_core9.fixedproducts
[13:52:54] Deleting unwanted file: prokka-1_core9/1_core9.ecn
[13:52:54] Deleting unwanted file: prokka-1_core9/1_core9.val
[13:52:54] Running: sed 's/COORDINATES: profile/COORDINATES:profile/' < prokka\-1_core9\/1_core9\.gbf > prokka\-1_core9\/1_core9\.gbk
sh: 1: cannot open prokka-1_core9/1_core9.gbf: No such file
[13:52:54] Could not run command: sed 's/COORDINATES: profile/COORDINATES:profile/' < prokka\-1_core9\/1_core9\.gbf > prokka\-1_core9\/1_core9\.gbk


This looks like it stems from the fact that the gbk file is no longer created, because, as suggested, I commented out all instances of the tbl2asn command. Do I need to troubleshoot the whole script, or is this something that can be taken care of by the author of the program. Not the Conda version, nor the version that sits in the prokka/bin/ directory is updated with capability to turn off the tbl2asn command, and all subsequent commands that deal with it's output files.

**Comment by tseemann** [comment]
@Arkadiy-Garber are you _sure_ you are using the latest versions of tbl2asn and prokka?
`conda update --all` inside your prokka environment?
do you have `conda-rorge` and `bioconda` in the correct order?

**Comment by Arkadiy-Garber** [comment]
Hi Torsten,

Yes, I am sure that I am using the latest version of tbl2asn and prokka. They were re-installed the same day that I posted the error message.

I was able to comment that line out: 
`sed 's/COORDINATES: profile/COORDINATES:profile/' < prokka-1_core9/1_core9.gbf > prokka-1_core9/1_core9.gbk`
and prokka finished without crashing. it provides the ORF calls and several related files, but does not actually provide the annotations.

I downloaded an older version of tbl2asn from a different server. This older version does _not_ give the: Segmentation fault (core dumped) error, but it over a year old. I was able to manually alter the script so that it used this older version of tbl2asn. It now does not crash, but also never finishes...it has been stuck on:

`[03:08:19] Running: ~/bin/tbl2asn -a s -q F -A 2_event108 -N 1 -y 'Annotated using prokka 1.13.3 from https://github.com/tseemann/prokka' -Z prokka-2_event108/2_event108.err -M n -V b -i prokka-2_event108/2_event108.fsa -f prokka-2_event108/2_event108.tbl 2> /dev/null` for a few days before I killed it.

thanks,
Arkadiy

**Comment by joergFLI** [comment]
Hi Torsten,
sorry to come back with this old issue.
I have installed latest version of prokka unsing conda but still have problems with tbl2asn beeing too old.
`conda activate prokka114`
`which prokka`
/home/software/miniconda3/envs/prokka114/bin/prokka
`prokka --version`
prokka 1.14.5
`which tbl2asn`
/home/software/miniconda3/envs/prokka114/bin/tbl2asn
`tbl2asn --version`
[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.

Indeed, there is an older tbl2asn as standard installation but I am running the tbl2asn provided within the conda-env.
Thanks

**Comment by phiweger** [comment]
can confirm, same problem w/ a fresh conda env and a new prokka install

**Comment by joergFLI** [comment]
This is helpful https://github.com/bioconda/bioconda-recipes/pull/20117
