### ISSUE TITLE
Prokka does not recognize blast 2.10 as >= blast 2.8

### ISSUE THREAD

**Issue by natachacouto** [tseemann/prokka#449]
Hey Torsten,

Just upgraded Blast to version 2.10 and I get the following message when I try to run prokka --setupdb
[13:34:45] Appending to PATH: /usr/local/Cellar/prokka/1.14.0/bin
[13:34:45] Cleaning databases in /usr/local/Cellar/prokka/1.14.0/db
[13:34:45] Cleaning complete.
[13:34:45] Looking for 'makeblastdb' - found /usr/local/bin/makeblastdb
[13:34:45] Determined makeblastdb version is 2.10
[13:34:45] Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again.

Can you help me with this?

**Comment by turpinpl** [comment]
natachacouto, I just ran into the same problem. Were you able to come up with a solution?

**Comment by gaboentropy** [comment]
Apparently this was fixed in prokka 1.14.5, but homebrew continues installing 1.14.0
If I knew anyting about homebrew I'd change it, but I don't have the time to learn right now.

**Comment by tseemann** [comment]
Thanks for reminding me I fixed it before I went on long holidays/vacation.

I see i never got the brew recipe accepted due to weird errors:
https://github.com/brewsci/homebrew-bio/pull/831

**Comment by gaboentropy** [comment]
Hum. In my mac, when I install the newest prokka, it fails because macs use an older perl version. In the meantime I changed the line in prokka referring to the minimum blastp and makeblastdb versions to 2.0 (I know that can bring trouble, but I did not have time to try more stuff). Maybe make perl a requirement so that a newer perl is installed by homebrew when prokka is installed as well?

**Comment by gaboentropy** [comment]
I meant. If I install it "by hand" rather than using homebrew.

**Comment by SabSN** [comment]
Hi, I have updated Prokka to version 1.14.5, but it still won't accept my blastp version 2.9, giving me the same error described here:

[13:24:38] Looking for 'blastp' - found /home/kma/miniconda3/bin/blastp
[13:24:38] Determined blastp version is 002002 from 'blastp: 2.2.31+'
[13:24:38] Prokka needs blastp 2.8 or higher. Please upgrade and try again.

Any solutions?

**Comment by gaboentropy** [comment]
SasSN,
That sounds like you truly have a very old blastp version, and that it is such that your prokka is seeing.
I installed prokka 1.14.15, finally, and it does accept either of 2.9.0+ and 2.10.0+

**Comment by mostueve** [comment]
Hi,
I am having the same problem with a conda install of Prokka.
My blastp version is definitely 2.10.0, prokka version is 1.13 (??).

So I guess I should use another way of installation in order to get the newest version of Prokka?

**Comment by tseemann** [comment]
I believe this was fixed a while back in Prokka 1.14. Please upgrade.

**Comment by jdwinkler-lanzatech** [comment]
Hi, 

I'm having the same problem using prokka v. 1.14.6 (from conda) and ncbi-blast+ v. 2.8.1-1+deb10u1. This is in a docker container base on miniconda3, so there shouldn;t be any issues with a broken miniconda installation.

**Comment by minna-miha** [comment]
> Hi, I have updated Prokka to version 1.14.5, but it still won't accept my blastp version 2.9, giving me the same error described here:
> 
> [13:24:38] Looking for 'blastp' - found /home/kma/miniconda3/bin/blastp
> [13:24:38] Determined blastp version is 002002 from 'blastp: 2.2.31+'
> [13:24:38] Prokka needs blastp 2.8 or higher. Please upgrade and try again.
> 
> Any solutions?

How did you update to prokka v 1.14.6? I tried this using a few methods (ex: conda update prokka) but it stays at 1.13.

**Comment by minna-miha** [comment]
> Thanks for reminding me I fixed it before I went on long holidays/vacation.
> 
> I see i never got the brew recipe accepted due to weird errors:
> [brewsci/homebrew-bio#831](https://github.com/brewsci/homebrew-bio/pull/831)

Is this supposed to be resolved? Because I am having the same issues:  prokka won't update beyond 1.13, and when I try to run my script it says I need blastp >2.2, even though I have v 2.10.

**Comment by 971202** [comment]
Just run on the node

**Comment by tianrenmaogithub** [comment]
I solved it by changing the script prokka. I changed the MINVERSION of blastp and makeblastdb to 2.1 so my blastp version 2.13 will be higher than 2.1. Try it.

**Comment by mmcguffi** [comment]
> I solved it by changing the script prokka. I changed the MINVERSION of blastp and makeblastdb to 2.1 so my blastp version 2.13 will be higher than 2.1. Try it.

I also had troubles getting prokka updated (using conda installation). Simply changing the script to 2.1 did indeed solve the issue

**Comment by yangm9** [comment]
I have tried many methods above to solve this issue, but it did nothing.
Finally, I changed MINVER  => "2.2" to MINVER  => "2.10" in the line 159 and 165 of prokka code file (~/miniconda3/envs/metawrap/bin/prokka in MetaWRAP v1.2.1), respectively.
Then, it worked well very much!!!

**Comment by TristansCloud** [comment]
> I solved it by changing the script prokka. I changed the MINVERSION of blastp and makeblastdb to 2.1 so my blastp version 2.13 will be higher than 2.1. Try it.

Just for the noobs like me who took a while to find where the prokka script is:

```
cd $CONDA_PREFIX/bin
nano prokka
# now within nano
^W # search for this text GETVER  => "blastp -version",
# Change MINVER  => "2.2" to MINVER  => "2.1"
# A few lines down is the option for makeblastdb, do the same change you did for blastp:
# Change MINVER  => "2.2" to MINVER  => "2.1"
```

**Comment by sam-mic** [comment]
> > I solved it by changing the script prokka. I changed the MINVERSION of blastp and makeblastdb to 2.1 so my blastp version 2.13 will be higher than 2.1. Try it.
> 
> Just for the noobs like me who took a while to find where the prokka script is:
> 
> ```
> cd $CONDA_PREFIX/bin
> nano prokka
> # now within nano
> ^W # search for this text GETVER  => "blastp -version",
> # Change MINVER  => "2.2" to MINVER  => "2.1"
> # A few lines down is the option for makeblastdb, do the same change you did for blastp:
> # Change MINVER  => "2.2" to MINVER  => "2.1"
> ```

Right solution. Actually string "2.2" is larger than "2.12".....

**Comment by YuLanSky** [comment]
This is  work! Even you never known about perl, you can DO it if you try!

cd $CONDA_PREFIX/bin
nano prokka
# now within nano
^W # search for this text GETVER  => "blastp -version",
# Change MINVER  => "2.2" to MINVER  => "2.1"
# A few lines down is the option for makeblastdb, do the same change you did for blastp:
# Change MINVER  => "2.2" to MINVER  => "2.1"

**Comment by romaro-gomes** [comment]
> > I solved it by changing the script prokka. I changed the MINVERSION of blastp and makeblastdb to 2.1 so my blastp version 2.13 will be higher than 2.1. Try it.
> 
> Just for the noobs like me who took a while to find where the prokka script is:
> 
> ```
> cd $CONDA_PREFIX/bin
> nano prokka
> # now within nano
> ^W # search for this text GETVER  => "blastp -version",
> # Change MINVER  => "2.2" to MINVER  => "2.1"
> # A few lines down is the option for makeblastdb, do the same change you did for blastp:
> # Change MINVER  => "2.2" to MINVER  => "2.1"
> ```

Thanks so much!

**Comment by jdwinkler-lanzatech** [comment]
Just FYI for everyone: this is not fixed in the latest version of prokka.
